dependencies:
  - name: kibana
    version: 0.17.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: logstash
    version: 1.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: elasticsearch-curator
    version: 1.0.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: elasticsearch-curator.enabled
  - name: filebeat
    version: 1.0.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: filebeat.enabled
