

kibana:
  image:
    #repository: "docker.elastic.co/kibana/kibana"
    repository: "docker.elastic.co/kibana/kibana-oss"
    tag: 6.3.2

  env:
    ELASTICSEARCH_URL: http://test-elasticsearch-discovery:9200
    ELASTICSEARCH_REQUESTTIMEOUT: 600000
    #XPACK_MONITORING_UI_ENABLED: true
    #XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: true
    #XPACK_MONITORING_ENABLED: true
    #XPACK_MONITORING_KIBANA_COLLECTION_ENABLED: true
    #XPACK_SECURITY_ENABLED: false
    #XPACK_ML_ENABLED: false
    #XPACK_WATCHER_ENABLED: false

  service:
    type: LoadBalancer


logstash:
  image:
    #repository: docker.elastic.co/logstash/logstash
    repository: docker.elastic.co/logstash/logstash-oss
    tag: 6.3.2

    #config:
      #xpack.monitoring.enabled: "true"
      #xpack.monitoring.elasticsearch.url: http://test-elasticsearch-discovery:9200


filebeat:
  config:
    output:
      logstash:
        hosts:
          - test-logstash:5044
        index: filebeat

  indexTemplate:
    upload: true
    elasticsearch:
      host: test-elasticsearch-discovery:9200
